/**
 * 한국어: 표준 에러 코드 카탈로그.
 *   resolver/service 가 user-facing 문장을 직접 만들지 않고 코드만 던진다.
 *   여기 등록된 코드는 i18n catalogs 에서 메시지로 해석된다.
 *
 * Tiếng Việt: Bảng mã lỗi chuẩn.
 */
export const ErrorCode = {
  // 공용
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',

  // 권한 / 테넌시
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  PERMISSION_DECORATOR_MISSING: 'PERMISSION_DECORATOR_MISSING',
  TENANT_CONTEXT_MISSING: 'TENANT_CONTEXT_MISSING',
  TENANT_SCOPE_AXIS_CONFLICT: 'TENANT_SCOPE_AXIS_CONFLICT',
  CROSS_TENANT_ACCESS_DENIED: 'CROSS_TENANT_ACCESS_DENIED',
  CROSS_CORPORATE_ACCESS_DENIED: 'CROSS_CORPORATE_ACCESS_DENIED',
  CROSS_BRAND_ACCESS_DENIED: 'CROSS_BRAND_ACCESS_DENIED',
  CORPORATE_CONTEXT_MISSING: 'CORPORATE_CONTEXT_MISSING',
  BRAND_CONTEXT_MISSING: 'BRAND_CONTEXT_MISSING',

  // 인증
  INVALID_USER_TYPE: 'INVALID_USER_TYPE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  TOO_MANY_LOGIN_ATTEMPTS: 'TOO_MANY_LOGIN_ATTEMPTS',
  INVALID_REFRESH_SESSION: 'INVALID_REFRESH_SESSION',
  REFRESH_SESSION_EXPIRED: 'REFRESH_SESSION_EXPIRED',
  REFRESH_SESSION_REUSED: 'REFRESH_SESSION_REUSED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_ALREADY_ASSIGNED: 'ROLE_ALREADY_ASSIGNED',
  SYSTEM_ROLE_DELETE_DENIED: 'SYSTEM_ROLE_DELETE_DENIED',
  SYSTEM_ROLE_READONLY: 'SYSTEM_ROLE_READONLY',
  SYSTEM_PERMISSION_READONLY: 'SYSTEM_PERMISSION_READONLY',
  PERMISSION_NOT_FOUND: 'PERMISSION_NOT_FOUND',
  ROLE_HAS_ACTIVE_ASSIGNMENTS: 'ROLE_HAS_ACTIVE_ASSIGNMENTS',
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  SCOPE_REQUIRED: 'SCOPE_REQUIRED',
  SCOPE_NOT_FOUND: 'SCOPE_NOT_FOUND',

  // 라이선스
  LICENSE_BRANCH_LIMIT_EXCEEDED: 'LICENSE_BRANCH_LIMIT_EXCEEDED',
  LICENSE_TERMINAL_LIMIT_EXCEEDED: 'LICENSE_TERMINAL_LIMIT_EXCEEDED',
  LICENSE_NOT_ACTIVE: 'LICENSE_NOT_ACTIVE',

  // 도메인 일반
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  INSUFFICIENT_DEPOSIT: 'INSUFFICIENT_DEPOSIT',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  SETTLEMENT_INVALID_STATUS_TRANSITION: 'SETTLEMENT_INVALID_STATUS_TRANSITION',
  CANNOT_REVERSE: 'CANNOT_REVERSE',
  ENROLLMENT_ALREADY_EXISTS: 'ENROLLMENT_ALREADY_EXISTS',
  CORPORATE_CREATE_PLATFORM_ONLY: 'CORPORATE_CREATE_PLATFORM_ONLY',
  ENROLLMENT_LIST_PLATFORM_ONLY: 'ENROLLMENT_LIST_PLATFORM_ONLY',
  PARENT_CATEGORY_BRAND_MISMATCH: 'PARENT_CATEGORY_BRAND_MISMATCH',
  MENU_CATEGORY_BRAND_MISMATCH: 'MENU_CATEGORY_BRAND_MISMATCH',
  DEPARTMENT_CORPORATE_MISMATCH: 'DEPARTMENT_CORPORATE_MISMATCH',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
} as const;

export type ErrorCodeKey = keyof typeof ErrorCode;
export type ErrorCodeValue = (typeof ErrorCode)[ErrorCodeKey];
