#pragma once

#include <string>

struct SellSlipRow {
    std::string SellDate;
    int OrderNo = 0;
    int ReceiptNo = 0;
    std::string EmpCode;
    int CustNum = 0;
    double OrderAmt = 0.0;
    double DcAmt = 0.0;
    double WorkAmt = 0.0;
    double ReceiveAmt = 0.0;
    double ReceivedAmt = 0.0;
    double ChangeAmt = 0.0;
    double CashAmt = 0.0;
    double CardAmt = 0.0;
    double PointAmt = 0.0;
    double CouponAmt = 0.0;
    double EtcAmt = 0.0;
    std::string OrderType;
    double TotalAmt = 0.0;
    std::string SellType;
    std::string PosNo;
    int TableCode = 0;
    std::string CustCode;
    std::string OrderEmpCode;
    double VatAmt = 0.0;
    double TipAmt = 0.0;
    std::string SaleDCListCode;
    std::string TableEmpCode;
    double ServiceAmt = 0.0;
    double DcEventAmt = 0.0;
    double MenuDcAmt = 0.0;
    std::string OrderMsgCode1;
    std::string OrderMsgCode2;
    std::string OrderMsgCode3;
    std::string SaleDcCode;
    int SavePoint = 0;
    std::string AdjustNo;
    double TickAmt = 0.0;
    std::string BCashReceipt;
    std::string GroupSet;
    std::string EndTimeDate;
    int EndTime = 0;
    std::string OrderPosNo;
    std::string FirstOrderDate;
    double FReceivedAmt1 = 0.0;
    double FReceivedAmt2 = 0.0;
    double FReceivedAmt3 = 0.0;
    int ReceivedCount = 0;
    double SaleDcAmt = 0.0;
    double TaxFree = 0.0;
    std::string Age;
    int Man = 0;
    int Woman = 0;
    int TakeOrderNo = 0;
    std::string AduFlag_CpQty;
    std::string SubCol1;
    double CashbagAmt = 0.0;
    double KeepAmt = 0.0;
    int StoreIndex = 0;
    double EdenredAmt = 0.0;
    double SelfAmt = 0.0;
    std::string DelFlag;
    std::string SubCol2;
    std::string SubCol3;
};
