import ScreenPreviewClient from '../ScreenPreviewClient';

export const dynamicParams = false;

export function generateStaticParams() {
  return [
    // 메인
    { slug: 'main-menu' },
    { slug: 'table' },
    { slug: 'order' },
    { slug: 'payment' },
    // 결제/정산
    { slug: 'payment-vn' },
    { slug: 'payment-quick-select' },
    { slug: 'payment-quick-select-vn' },
    { slug: 'order-payment' },
    { slug: 'order-payment-quick' },
    { slug: 'dutch-pay' },
    { slug: 'dutch-pay-people' },
    { slug: 'dutch-pay-item' },
    { slug: 'payment-etc' },
    { slug: 'payment-memo' },
    { slug: 'async-payment-noti' },
    // 주문/메뉴
    { slug: 'order-quick-select' },
    { slug: 'order-item-detail' },
    { slug: 'order-item-info' },
    { slug: 'order-item-list' },
    { slug: 'order-message' },
    { slug: 'plu-set' },
    { slug: 'set-menu' },
    // 테이블/예약
    { slug: 'table-quick-select' },
    { slug: 'table-select' },
    { slug: 'table-message' },
    { slug: 'table-group-checkout' },
    { slug: 'appointment' },
    { slug: 'appointment-table-view' },
    // 배달
    { slug: 'delivery' },
    { slug: 'delivery-address' },
    { slug: 'delivery-print' },
    { slug: 'delivery-agency' },
    { slug: 'delivery-address-input' },
    { slug: 'delivery-cid' },
    // 고객
    { slug: 'customer-register' },
    { slug: 'customer-search' },
    { slug: 'customer-input' },
    { slug: 'customer-info' },
    { slug: 'customer-detail' },
    { slug: 'customer-all-register' },
    { slug: 'customer-item-in' },
    { slug: 'customer-item-sell' },
    { slug: 'customer-item-use' },
    { slug: 'customer-keep' },
    { slug: 'chain-customer-list' },
    // 직원
    { slug: 'employee-select' },
    { slug: 'employee-call' },
    { slug: 'employee-alert' },
    { slug: 'attendance' },
    { slug: 'attendance-pay' },
    { slug: 'attendance-modify' },
    { slug: 'attendance-settings' },
    // 재고/매입/장부
    { slug: 'stock' },
    { slug: 'stock-input' },
    { slug: 'stock-view' },
    { slug: 'stock-date-view' },
    { slug: 'stock-account' },
    { slug: 'stock-supply' },
    { slug: 'purchase' },
    { slug: 'purchase-modify' },
    { slug: 'purchase-view' },
    { slug: 'cash-inout' },
    { slug: 'cash-inout-input' },
    { slug: 'ledger-register' },
    { slug: 'ledger-input' },
    { slug: 'ledger-view' },
    { slug: 'item-register' },
    // 상품권/포인트
    { slug: 'gift-manage' },
    { slug: 'gift-register' },
    { slug: 'gift-use' },
    { slug: 'coupon-use' },
    { slug: 'point-save' },
    { slug: 'card-list' },
    // 결제수단
    { slug: 'kakaopay' },
    { slug: 'zalopay' },
    { slug: 'hjvietpay' },
    { slug: 'infoplus-bidv' },
    { slug: 'infoplus-shinhan' },
    { slug: 'infoplus-woori' },
    { slug: 'napas' },
    { slug: 'kakaotalk-alert' },
    // 영수증/출력
    { slug: 'receipt-choice' },
    { slug: 'simple-receipt' },
    { slug: 'barcode-print' },
    { slug: 'barcode-settings' },
    { slug: 'kdr-receipt' },
    // 테이블오더
    { slug: 'table-order-control' },
    { slug: 'table-order-manager' },
    { slug: 'table-order-receive' },
    { slug: 'table-order-state' },
    { slug: 'table-order-soldout' },
    // 주방 디스플레이
    { slug: 'kitchen' },
    { slug: 'kitchen-v2' },
    { slug: 'kitchen-settings' },
    { slug: 'call-number-display' },
    { slug: 'call-number-settings' },
    // 유틸리티
    { slug: 'login' },
    { slug: 'auth' },
    { slug: 'no-permission' },
    { slug: 'numpad' },
    { slug: 'phone-numpad' },
    { slug: 'keyboard' },
    { slug: 'message-box' },
    { slug: 'message-view' },
    { slug: 'text-search' },
    { slug: 'checkout' },
    { slug: 'resell' },
    { slug: 'sell-void' },
    { slug: 'sell-view-select' },
    { slug: 'sell-list-view' },
    { slug: 'auto-end-work' },
    { slug: 'sign-touch' },
    // 레거시 RC 추출 — 메인 POS (Restaurant.rc) — 67개
    { slug: 'rc-restaurant-dialog' },
    { slug: 'rc-login' },
    { slug: 'rc-table-dialog' },
    { slug: 'rc-order-dialog' },
    { slug: 'rc-oracc-dialog' },
    { slug: 'rc-account-dialog' },
    { slug: 'rc-account-dialog-vn' },
    { slug: 'rc-empsel' },
    { slug: 'rc-custsel' },
    { slug: 'rc-custinput' },
    { slug: 'rc-custregi' },
    { slug: 'rc-cust-detail' },
    { slug: 'rc-cust-keep' },
    { slug: 'rc-custdeli' },
    { slug: 'rc-custdeli2' },
    { slug: 'rc-custdeli-addr' },
    { slug: 'rc-custdeli-prn' },
    { slug: 'rc-emp-diligence' },
    { slug: 'rc-stock-input' },
    { slug: 'rc-stock-view' },
    { slug: 'rc-inout-dialog' },
    { slug: 'rc-sellview' },
    { slug: 'rc-sellview-select' },
    { slug: 'rc-selllistview' },
    { slug: 'rc-saledc' },
    { slug: 'rc-autowork' },
    { slug: 'rc-iniset' },
    { slug: 'rc-numpad' },
    { slug: 'rc-phone-numpad' },
    { slug: 'rc-phone-numpad2' },
    { slug: 'rc-message-dialog' },
    { slug: 'rc-unpermission' },
    { slug: 'rc-tickserch' },
    { slug: 'rc-gettick-dialog' },
    { slug: 'rc-groupsel-dlg' },
    { slug: 'rc-table-bselect' },
    { slug: 'rc-oracc-bselect' },
    { slug: 'rc-account-bselect' },
    { slug: 'rc-account-bselect-vn' },
    { slug: 'rc-contentview' },
    { slug: 'rc-contentview2' },
    { slug: 'rc-pointsavesell' },
    { slug: 'rc-gethold-dlg' },
    { slug: 'rc-getitemserver' },
    { slug: 'rc-menumove' },
    { slug: 'rc-moveimg-dlg' },
    { slug: 'rc-order-pluset' },
    { slug: 'rc-martsell-dlg' },
    { slug: 'rc-purchasemgr-dlg' },
    { slug: 'rc-pur-stomodify' },
    { slug: 'rc-itemregi' },
    { slug: 'rc-item-search' },
    { slug: 'rc-catcashmgr-dlg' },
    { slug: 'rc-cid-numview' },
    { slug: 'rc-inputandcust' },
    { slug: 'rc-tablemsg-dlg' },
    { slug: 'rc-zalopay-qr' },
    { slug: 'rc-napas-qr' },
    { slug: 'rc-hjvietpay-dlg' },
    { slug: 'rc-infoplus-shinhan-qr' },
    { slug: 'rc-infoplus-bidv-qr' },
    { slug: 'rc-infoplus-woori-qr' },
    { slug: 'rc-async-paynoti-dlg' },
    { slug: 'rc-kakaotalk-alim' },
    { slug: 'rc-kiosk-dlg' },
    { slug: 'rc-kio-optitem' },
    { slug: 'rc-viettel-issuance' },
    // 레거시 RC 추출 — 설정 앱 (RestaurantSet.rc) — 44개
    { slug: 'rc-set-restaurantset-dialog' },
    { slug: 'rc-set-basicset' },
    { slug: 'rc-set-companyinfo' },
    { slug: 'rc-set-deviceset' },
    { slug: 'rc-set-empinput' },
    { slug: 'rc-set-custinfoset' },
    { slug: 'rc-set-iteminput' },
    { slug: 'rc-set-iteminput-detail' },
    { slug: 'rc-set-itemset' },
    { slug: 'rc-set-item-grpos' },
    { slug: 'rc-set-pay-mgr' },
    { slug: 'rc-set-print-mgr' },
    { slug: 'rc-set-kio-mgr' },
    { slug: 'rc-set-qrpay-mgr' },
    { slug: 'rc-set-cardreader-mgr' },
    { slug: 'rc-set-zalooa-mgr' },
    { slug: 'rc-set-zalooa-payment-dlg' },
    { slug: 'rc-set-zalooa-appointment-dlg' },
    { slug: 'rc-set-zalopay-qr' },
    { slug: 'rc-set-saledc' },
    { slug: 'rc-set-eventset' },
    { slug: 'rc-set-favorites' },
    { slug: 'rc-set-grpappdlg' },
    { slug: 'rc-set-inoutset' },
    { slug: 'rc-set-ordermsg' },
    { slug: 'rc-set-numpad' },
    { slug: 'rc-set-tablemsg' },
    { slug: 'rc-set-storeinfo' },
    { slug: 'rc-set-supply-dlg' },
    { slug: 'rc-set-basic-code' },
    { slug: 'rc-set-datadel' },
    { slug: 'rc-set-iniset' },
    { slug: 'rc-set-simplereceipt' },
    { slug: 'rc-set-selectselldel-dlg' },
    { slug: 'rc-set-printset-dlg' },
    { slug: 'rc-set-printbill-dlg' },
    { slug: 'rc-set-printrece-dlg' },
    { slug: 'rc-set-printreg-dlg' },
    { slug: 'rc-set-printmsg-dlg' },
    { slug: 'rc-set-printqr-dlg' },
    { slug: 'rc-set-pay-taxref' },
    { slug: 'rc-set-pay-taxseller-dlg' },
    { slug: 'rc-set-paycoset-dlg' },
    { slug: 'rc-set-etcsetv2-dlg' },
  ];
}

export default async function ScreenPreview({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  return <ScreenPreviewClient slug={slug} />;
}
